### ISSUE TITLE
Remove "coming up" section until we have anything to show

### ISSUE THREAD

**Issue by campoy** [src-d/talks#95]
The current pages makes it look like there's no talks at all on the page.

<img width="887" alt="screen shot 2017-11-10 at 1 51 59 pm" src="https://user-images.githubusercontent.com/2237452/32659298-5d37dda6-c61e-11e7-887d-2683ee9a2109.png">

The simplest fix to this is to remove the section altogether, maybe conditionally if we can detect when there are upcoming talks.

**Comment by dpordomingo** [comment]
It needs a review from a design pov since removing the "coming soon" card breaks the layout
![image](https://user-images.githubusercontent.com/2437584/32665607-2bf69ee6-c635-11e7-998f-648d3a53821c.png)

A quick&dirty alternative would be to remove the card, but leaving a min-height for the header, so it would be somehow fixed.
_example:_
![image](https://user-images.githubusercontent.com/2437584/32665674-671e994c-c635-11e7-924c-6ed98852e449.png)

Anyhow, I think it would be better if the content of the first section would be the past talks when there are no upcoming talks. That way, the "most relevant content" in that scenario would be our last sessions, instead of "nothing". 
_example:_
![talks](https://user-images.githubusercontent.com/2437584/32666019-718c4a7c-c636-11e7-9e4f-ead019ba9fe7.png)

What do you think about it?
/cc @marnovo

**Comment by campoy** [comment]
I like the last version best, but how does it display in a narrower screen?

**Comment by dpordomingo** [comment]
Not that bad...
(like the current design, I mean)
_example:_
![talks_iphone_small](https://user-images.githubusercontent.com/2437584/32669802-19339356-c642-11e7-89e2-cebe7f31d008.png)

**Comment by campoy** [comment]
That looks pretty good, SGTM

**Comment by campoy** [comment]
This will be handled by the website redesign.

**Comment by marnovo** [comment]
Indeed. 👍
